server:
  port: 3333
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.199.119:3306/bigdata?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource